// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvjlvnpebawaahjtbub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdmpsdm5wZWJhd2FhaGp0YnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MzMwNDQsImV4cCI6MjA4ODUwOTA0NH0.SMs-ySqx9U1fJadIyYpoYUCpdjcc2JvZPhidkfGYfVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});